/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assert Response</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.AssertResponse#getComparacion <em>Comparacion</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getAssertResponse()
 * @model
 * @generated
 */
public interface AssertResponse extends EObject
{
  /**
   * Returns the value of the '<em><b>Comparacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparacion</em>' containment reference.
   * @see #setComparacion(Comparacion)
   * @see org.xtext.example.mydsl.rest.RestPackage#getAssertResponse_Comparacion()
   * @model containment="true"
   * @generated
   */
  Comparacion getComparacion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.AssertResponse#getComparacion <em>Comparacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparacion</em>' containment reference.
   * @see #getComparacion()
   * @generated
   */
  void setComparacion(Comparacion value);

} // AssertResponse
