/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.Assertion#getAssertResponse <em>Assert Response</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getAssertion()
 * @model
 * @generated
 */
public interface Assertion extends EObject
{
  /**
   * Returns the value of the '<em><b>Assert Response</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.rest.AssertResponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assert Response</em>' containment reference list.
   * @see org.xtext.example.mydsl.rest.RestPackage#getAssertion_AssertResponse()
   * @model containment="true"
   * @generated
   */
  EList<AssertResponse> getAssertResponse();

} // Assertion
