/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.Atributo#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Atributo#isArray <em>Array</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Atributo#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Atributo#getMocktype <em>Mocktype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getAtributo()
 * @model
 * @generated
 */
public interface Atributo extends EObject
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' containment reference.
   * @see #setTipo(TipoElemento)
   * @see org.xtext.example.mydsl.rest.RestPackage#getAtributo_Tipo()
   * @model containment="true"
   * @generated
   */
  TipoElemento getTipo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Atributo#getTipo <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' containment reference.
   * @see #getTipo()
   * @generated
   */
  void setTipo(TipoElemento value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(boolean)
   * @see org.xtext.example.mydsl.rest.RestPackage#getAtributo_Array()
   * @model
   * @generated
   */
  boolean isArray();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Atributo#isArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #isArray()
   * @generated
   */
  void setArray(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.rest.RestPackage#getAtributo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Atributo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mocktype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mocktype</em>' containment reference.
   * @see #setMocktype(Mock)
   * @see org.xtext.example.mydsl.rest.RestPackage#getAtributo_Mocktype()
   * @model containment="true"
   * @generated
   */
  Mock getMocktype();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Atributo#getMocktype <em>Mocktype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mocktype</em>' containment reference.
   * @see #getMocktype()
   * @generated
   */
  void setMocktype(Mock value);

} // Atributo
