/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparacion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.Comparacion#getEntidad <em>Entidad</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Comparacion#getAtributo <em>Atributo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Comparacion#getMetodo <em>Metodo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Comparacion#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getComparacion()
 * @model
 * @generated
 */
public interface Comparacion extends EObject
{
  /**
   * Returns the value of the '<em><b>Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidad</em>' reference.
   * @see #setEntidad(Entidad)
   * @see org.xtext.example.mydsl.rest.RestPackage#getComparacion_Entidad()
   * @model
   * @generated
   */
  Entidad getEntidad();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Comparacion#getEntidad <em>Entidad</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entidad</em>' reference.
   * @see #getEntidad()
   * @generated
   */
  void setEntidad(Entidad value);

  /**
   * Returns the value of the '<em><b>Atributo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributo</em>' reference.
   * @see #setAtributo(Atributo)
   * @see org.xtext.example.mydsl.rest.RestPackage#getComparacion_Atributo()
   * @model
   * @generated
   */
  Atributo getAtributo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Comparacion#getAtributo <em>Atributo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atributo</em>' reference.
   * @see #getAtributo()
   * @generated
   */
  void setAtributo(Atributo value);

  /**
   * Returns the value of the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metodo</em>' reference.
   * @see #setMetodo(Metodo)
   * @see org.xtext.example.mydsl.rest.RestPackage#getComparacion_Metodo()
   * @model
   * @generated
   */
  Metodo getMetodo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Comparacion#getMetodo <em>Metodo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metodo</em>' reference.
   * @see #getMetodo()
   * @generated
   */
  void setMetodo(Metodo value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' reference.
   * @see #setParam(PathParam)
   * @see org.xtext.example.mydsl.rest.RestPackage#getComparacion_Param()
   * @model
   * @generated
   */
  PathParam getParam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Comparacion#getParam <em>Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' reference.
   * @see #getParam()
   * @generated
   */
  void setParam(PathParam value);

} // Comparacion
