/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DELETE</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getDELETE()
 * @model
 * @generated
 */
public interface DELETE extends Metodo
{
} // DELETE
