/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entidad Mock</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getEntidadMock()
 * @model
 * @generated
 */
public interface EntidadMock extends Entidad
{
} // EntidadMock
