/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.Map#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Map#getEntidadMap <em>Entidad Map</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Map#getAtributo <em>Atributo</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getMap()
 * @model
 * @generated
 */
public interface Map extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(MapName)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMap_Name()
   * @model containment="true"
   * @generated
   */
  MapName getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Map#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(MapName value);

  /**
   * Returns the value of the '<em><b>Entidad Map</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidad Map</em>' reference.
   * @see #setEntidadMap(Entidad)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMap_EntidadMap()
   * @model
   * @generated
   */
  Entidad getEntidadMap();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Map#getEntidadMap <em>Entidad Map</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entidad Map</em>' reference.
   * @see #getEntidadMap()
   * @generated
   */
  void setEntidadMap(Entidad value);

  /**
   * Returns the value of the '<em><b>Atributo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributo</em>' reference.
   * @see #setAtributo(Atributo)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMap_Atributo()
   * @model
   * @generated
   */
  Atributo getAtributo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Map#getAtributo <em>Atributo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atributo</em>' reference.
   * @see #getAtributo()
   * @generated
   */
  void setAtributo(Atributo value);

} // Map
