/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.MapName#getMetodo <em>Metodo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.MapName#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getMapName()
 * @model
 * @generated
 */
public interface MapName extends EObject
{
  /**
   * Returns the value of the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metodo</em>' reference.
   * @see #setMetodo(Metodo)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMapName_Metodo()
   * @model
   * @generated
   */
  Metodo getMetodo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.MapName#getMetodo <em>Metodo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metodo</em>' reference.
   * @see #getMetodo()
   * @generated
   */
  void setMetodo(Metodo value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' reference.
   * @see #setParam(PathParam)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMapName_Param()
   * @model
   * @generated
   */
  PathParam getParam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.MapName#getParam <em>Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' reference.
   * @see #getParam()
   * @generated
   */
  void setParam(PathParam value);

} // MapName
