/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metodo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.Metodo#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Metodo#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.Metodo#getResponse <em>Response</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getMetodo()
 * @model
 * @generated
 */
public interface Metodo extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMetodo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Metodo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' containment reference.
   * @see #setPath(URL)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMetodo_Path()
   * @model containment="true"
   * @generated
   */
  URL getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Metodo#getPath <em>Path</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' containment reference.
   * @see #getPath()
   * @generated
   */
  void setPath(URL value);

  /**
   * Returns the value of the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' containment reference.
   * @see #setResponse(Response)
   * @see org.xtext.example.mydsl.rest.RestPackage#getMetodo_Response()
   * @model containment="true"
   * @generated
   */
  Response getResponse();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.Metodo#getResponse <em>Response</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response</em>' containment reference.
   * @see #getResponse()
   * @generated
   */
  void setResponse(Response value);

} // Metodo
