/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PUT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.PUT#getRequest <em>Request</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rest.RestPackage#getPUT()
 * @model
 * @generated
 */
public interface PUT extends Metodo
{
  /**
   * Returns the value of the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Request</em>' containment reference.
   * @see #setRequest(Request)
   * @see org.xtext.example.mydsl.rest.RestPackage#getPUT_Request()
   * @model containment="true"
   * @generated
   */
  Request getRequest();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rest.PUT#getRequest <em>Request</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Request</em>' containment reference.
   * @see #getRequest()
   * @generated
   */
  void setRequest(Request value);

} // PUT
