/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.rest.RestPackage
 * @generated
 */
public interface RestFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestFactory eINSTANCE = org.xtext.example.mydsl.rest.impl.RestFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Test</em>'.
   * @generated
   */
  Test createTest();

  /**
   * Returns a new object of class '<em>Assertion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assertion</em>'.
   * @generated
   */
  Assertion createAssertion();

  /**
   * Returns a new object of class '<em>Assert Response</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assert Response</em>'.
   * @generated
   */
  AssertResponse createAssertResponse();

  /**
   * Returns a new object of class '<em>Comparacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comparacion</em>'.
   * @generated
   */
  Comparacion createComparacion();

  /**
   * Returns a new object of class '<em>Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping</em>'.
   * @generated
   */
  Mapping createMapping();

  /**
   * Returns a new object of class '<em>Map</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map</em>'.
   * @generated
   */
  Map createMap();

  /**
   * Returns a new object of class '<em>Map Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Name</em>'.
   * @generated
   */
  MapName createMapName();

  /**
   * Returns a new object of class '<em>Metodo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metodo</em>'.
   * @generated
   */
  Metodo createMetodo();

  /**
   * Returns a new object of class '<em>DELETE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DELETE</em>'.
   * @generated
   */
  DELETE createDELETE();

  /**
   * Returns a new object of class '<em>POST</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POST</em>'.
   * @generated
   */
  POST createPOST();

  /**
   * Returns a new object of class '<em>PUT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PUT</em>'.
   * @generated
   */
  PUT createPUT();

  /**
   * Returns a new object of class '<em>GET</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GET</em>'.
   * @generated
   */
  GET createGET();

  /**
   * Returns a new object of class '<em>Response</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Response</em>'.
   * @generated
   */
  Response createResponse();

  /**
   * Returns a new object of class '<em>Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Request</em>'.
   * @generated
   */
  Request createRequest();

  /**
   * Returns a new object of class '<em>URL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>URL</em>'.
   * @generated
   */
  URL createURL();

  /**
   * Returns a new object of class '<em>Path Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Param</em>'.
   * @generated
   */
  PathParam createPathParam();

  /**
   * Returns a new object of class '<em>Query Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Param</em>'.
   * @generated
   */
  QueryParam createQueryParam();

  /**
   * Returns a new object of class '<em>Entidad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidad</em>'.
   * @generated
   */
  Entidad createEntidad();

  /**
   * Returns a new object of class '<em>Entidad Mock</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidad Mock</em>'.
   * @generated
   */
  EntidadMock createEntidadMock();

  /**
   * Returns a new object of class '<em>Entidad Simple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidad Simple</em>'.
   * @generated
   */
  EntidadSimple createEntidadSimple();

  /**
   * Returns a new object of class '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atributo</em>'.
   * @generated
   */
  Atributo createAtributo();

  /**
   * Returns a new object of class '<em>Mock</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mock</em>'.
   * @generated
   */
  Mock createMock();

  /**
   * Returns a new object of class '<em>Tipo Elemento</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tipo Elemento</em>'.
   * @generated
   */
  TipoElemento createTipoElemento();

  /**
   * Returns a new object of class '<em>Tipo Entidad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tipo Entidad</em>'.
   * @generated
   */
  TipoEntidad createTipoEntidad();

  /**
   * Returns a new object of class '<em>Tipo Basico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tipo Basico</em>'.
   * @generated
   */
  TipoBasico createTipoBasico();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RestPackage getRestPackage();

} //RestFactory
