/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.rest.RestFactory
 * @model kind="package"
 * @generated
 */
public interface RestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Rest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestPackage eINSTANCE = org.xtext.example.mydsl.rest.impl.RestPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.ModelImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTIDADES = 0;

  /**
   * The feature id for the '<em><b>Metodos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__METODOS = 1;

  /**
   * The feature id for the '<em><b>Tests</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TESTS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.TestImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTest()
   * @generated
   */
  int TEST = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__NAME = 0;

  /**
   * The feature id for the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__SERVICE = 1;

  /**
   * The feature id for the '<em><b>Mapping</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__MAPPING = 2;

  /**
   * The feature id for the '<em><b>Assertion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__ASSERTION = 3;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.AssertionImpl <em>Assertion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.AssertionImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAssertion()
   * @generated
   */
  int ASSERTION = 2;

  /**
   * The feature id for the '<em><b>Assert Response</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION__ASSERT_RESPONSE = 0;

  /**
   * The number of structural features of the '<em>Assertion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.AssertResponseImpl <em>Assert Response</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.AssertResponseImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAssertResponse()
   * @generated
   */
  int ASSERT_RESPONSE = 3;

  /**
   * The feature id for the '<em><b>Comparacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_RESPONSE__COMPARACION = 0;

  /**
   * The number of structural features of the '<em>Assert Response</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_RESPONSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.ComparacionImpl <em>Comparacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.ComparacionImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getComparacion()
   * @generated
   */
  int COMPARACION = 4;

  /**
   * The feature id for the '<em><b>Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACION__ENTIDAD = 0;

  /**
   * The feature id for the '<em><b>Atributo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACION__ATRIBUTO = 1;

  /**
   * The feature id for the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACION__METODO = 2;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACION__PARAM = 3;

  /**
   * The number of structural features of the '<em>Comparacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.MappingImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 5;

  /**
   * The feature id for the '<em><b>Maps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__MAPS = 0;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.MapImpl <em>Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.MapImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMap()
   * @generated
   */
  int MAP = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP__NAME = 0;

  /**
   * The feature id for the '<em><b>Entidad Map</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP__ENTIDAD_MAP = 1;

  /**
   * The feature id for the '<em><b>Atributo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP__ATRIBUTO = 2;

  /**
   * The number of structural features of the '<em>Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.MapNameImpl <em>Map Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.MapNameImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMapName()
   * @generated
   */
  int MAP_NAME = 7;

  /**
   * The feature id for the '<em><b>Metodo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_NAME__METODO = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_NAME__PARAM = 1;

  /**
   * The number of structural features of the '<em>Map Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_NAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.MetodoImpl <em>Metodo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.MetodoImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMetodo()
   * @generated
   */
  int METODO = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO__NAME = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO__PATH = 1;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO__RESPONSE = 2;

  /**
   * The number of structural features of the '<em>Metodo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METODO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.DELETEImpl <em>DELETE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.DELETEImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getDELETE()
   * @generated
   */
  int DELETE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__NAME = METODO__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__PATH = METODO__PATH;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__RESPONSE = METODO__RESPONSE;

  /**
   * The number of structural features of the '<em>DELETE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_FEATURE_COUNT = METODO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.POSTImpl <em>POST</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.POSTImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPOST()
   * @generated
   */
  int POST = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST__NAME = METODO__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST__PATH = METODO__PATH;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST__RESPONSE = METODO__RESPONSE;

  /**
   * The feature id for the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST__REQUEST = METODO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>POST</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST_FEATURE_COUNT = METODO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.PUTImpl <em>PUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.PUTImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPUT()
   * @generated
   */
  int PUT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__NAME = METODO__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__PATH = METODO__PATH;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__RESPONSE = METODO__RESPONSE;

  /**
   * The feature id for the '<em><b>Request</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__REQUEST = METODO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>PUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_FEATURE_COUNT = METODO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.GETImpl <em>GET</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.GETImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getGET()
   * @generated
   */
  int GET = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__NAME = METODO__NAME;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__PATH = METODO__PATH;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__RESPONSE = METODO__RESPONSE;

  /**
   * The number of structural features of the '<em>GET</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_FEATURE_COUNT = METODO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.ResponseImpl <em>Response</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.ResponseImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getResponse()
   * @generated
   */
  int RESPONSE = 13;

  /**
   * The feature id for the '<em><b>Tipo Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE__TIPO_RESPONSE = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE__ARRAY = 1;

  /**
   * The number of structural features of the '<em>Response</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.RequestImpl <em>Request</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.RequestImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getRequest()
   * @generated
   */
  int REQUEST = 14;

  /**
   * The feature id for the '<em><b>Tipo Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUEST__TIPO_RESPONSE = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUEST__ARRAY = 1;

  /**
   * The number of structural features of the '<em>Request</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.URLImpl <em>URL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.URLImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getURL()
   * @generated
   */
  int URL = 15;

  /**
   * The feature id for the '<em><b>Pathparam</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__PATHPARAM = 0;

  /**
   * The feature id for the '<em><b>Queryparam</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__QUERYPARAM = 1;

  /**
   * The number of structural features of the '<em>URL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.PathParamImpl <em>Path Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.PathParamImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPathParam()
   * @generated
   */
  int PATH_PARAM = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_PARAM__NAME = 0;

  /**
   * The number of structural features of the '<em>Path Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_PARAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.QueryParamImpl <em>Query Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.QueryParamImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getQueryParam()
   * @generated
   */
  int QUERY_PARAM = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_PARAM__NAME = 0;

  /**
   * The number of structural features of the '<em>Query Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_PARAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.EntidadImpl <em>Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.EntidadImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidad()
   * @generated
   */
  int ENTIDAD = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__NAME = 0;

  /**
   * The feature id for the '<em><b>Atributos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__ATRIBUTOS = 1;

  /**
   * The number of structural features of the '<em>Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.EntidadMockImpl <em>Entidad Mock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.EntidadMockImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidadMock()
   * @generated
   */
  int ENTIDAD_MOCK = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_MOCK__NAME = ENTIDAD__NAME;

  /**
   * The feature id for the '<em><b>Atributos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_MOCK__ATRIBUTOS = ENTIDAD__ATRIBUTOS;

  /**
   * The number of structural features of the '<em>Entidad Mock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_MOCK_FEATURE_COUNT = ENTIDAD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.EntidadSimpleImpl <em>Entidad Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.EntidadSimpleImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidadSimple()
   * @generated
   */
  int ENTIDAD_SIMPLE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_SIMPLE__NAME = ENTIDAD__NAME;

  /**
   * The feature id for the '<em><b>Atributos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_SIMPLE__ATRIBUTOS = ENTIDAD__ATRIBUTOS;

  /**
   * The number of structural features of the '<em>Entidad Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_SIMPLE_FEATURE_COUNT = ENTIDAD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.AtributoImpl <em>Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.AtributoImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAtributo()
   * @generated
   */
  int ATRIBUTO = 21;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__TIPO = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__NAME = 2;

  /**
   * The feature id for the '<em><b>Mocktype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__MOCKTYPE = 3;

  /**
   * The number of structural features of the '<em>Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.MockImpl <em>Mock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.MockImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMock()
   * @generated
   */
  int MOCK = 22;

  /**
   * The feature id for the '<em><b>Pk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOCK__PK = 0;

  /**
   * The number of structural features of the '<em>Mock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.TipoElementoImpl <em>Tipo Elemento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.TipoElementoImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoElemento()
   * @generated
   */
  int TIPO_ELEMENTO = 23;

  /**
   * The number of structural features of the '<em>Tipo Elemento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ELEMENTO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.TipoEntidadImpl <em>Tipo Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.TipoEntidadImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoEntidad()
   * @generated
   */
  int TIPO_ENTIDAD = 24;

  /**
   * The feature id for the '<em><b>Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ENTIDAD__ENTIDAD = TIPO_ELEMENTO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tipo Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_ENTIDAD_FEATURE_COUNT = TIPO_ELEMENTO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.rest.impl.TipoBasicoImpl <em>Tipo Basico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.rest.impl.TipoBasicoImpl
   * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoBasico()
   * @generated
   */
  int TIPO_BASICO = 25;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_BASICO__NAME = TIPO_ELEMENTO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tipo Basico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_BASICO_FEATURE_COUNT = TIPO_ELEMENTO_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.rest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Model#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see org.xtext.example.mydsl.rest.Model#getEntidades()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entidades();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Model#getMetodos <em>Metodos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metodos</em>'.
   * @see org.xtext.example.mydsl.rest.Model#getMetodos()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Metodos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Model#getTests <em>Tests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tests</em>'.
   * @see org.xtext.example.mydsl.rest.Model#getTests()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tests();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.example.mydsl.rest.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Test#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.Test#getName()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Test#getService <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service</em>'.
   * @see org.xtext.example.mydsl.rest.Test#getService()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Service();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Test#getMapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mapping</em>'.
   * @see org.xtext.example.mydsl.rest.Test#getMapping()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Mapping();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Test#getAssertion <em>Assertion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assertion</em>'.
   * @see org.xtext.example.mydsl.rest.Test#getAssertion()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Assertion();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Assertion <em>Assertion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assertion</em>'.
   * @see org.xtext.example.mydsl.rest.Assertion
   * @generated
   */
  EClass getAssertion();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Assertion#getAssertResponse <em>Assert Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assert Response</em>'.
   * @see org.xtext.example.mydsl.rest.Assertion#getAssertResponse()
   * @see #getAssertion()
   * @generated
   */
  EReference getAssertion_AssertResponse();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.AssertResponse <em>Assert Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assert Response</em>'.
   * @see org.xtext.example.mydsl.rest.AssertResponse
   * @generated
   */
  EClass getAssertResponse();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.AssertResponse#getComparacion <em>Comparacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comparacion</em>'.
   * @see org.xtext.example.mydsl.rest.AssertResponse#getComparacion()
   * @see #getAssertResponse()
   * @generated
   */
  EReference getAssertResponse_Comparacion();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Comparacion <em>Comparacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparacion</em>'.
   * @see org.xtext.example.mydsl.rest.Comparacion
   * @generated
   */
  EClass getComparacion();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Comparacion#getEntidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entidad</em>'.
   * @see org.xtext.example.mydsl.rest.Comparacion#getEntidad()
   * @see #getComparacion()
   * @generated
   */
  EReference getComparacion_Entidad();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Comparacion#getAtributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Atributo</em>'.
   * @see org.xtext.example.mydsl.rest.Comparacion#getAtributo()
   * @see #getComparacion()
   * @generated
   */
  EReference getComparacion_Atributo();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Comparacion#getMetodo <em>Metodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metodo</em>'.
   * @see org.xtext.example.mydsl.rest.Comparacion#getMetodo()
   * @see #getComparacion()
   * @generated
   */
  EReference getComparacion_Metodo();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Comparacion#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see org.xtext.example.mydsl.rest.Comparacion#getParam()
   * @see #getComparacion()
   * @generated
   */
  EReference getComparacion_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see org.xtext.example.mydsl.rest.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Mapping#getMaps <em>Maps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Maps</em>'.
   * @see org.xtext.example.mydsl.rest.Mapping#getMaps()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_Maps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Map <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map</em>'.
   * @see org.xtext.example.mydsl.rest.Map
   * @generated
   */
  EClass getMap();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Map#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.Map#getName()
   * @see #getMap()
   * @generated
   */
  EReference getMap_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Map#getEntidadMap <em>Entidad Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entidad Map</em>'.
   * @see org.xtext.example.mydsl.rest.Map#getEntidadMap()
   * @see #getMap()
   * @generated
   */
  EReference getMap_EntidadMap();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.Map#getAtributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Atributo</em>'.
   * @see org.xtext.example.mydsl.rest.Map#getAtributo()
   * @see #getMap()
   * @generated
   */
  EReference getMap_Atributo();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.MapName <em>Map Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Name</em>'.
   * @see org.xtext.example.mydsl.rest.MapName
   * @generated
   */
  EClass getMapName();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.MapName#getMetodo <em>Metodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metodo</em>'.
   * @see org.xtext.example.mydsl.rest.MapName#getMetodo()
   * @see #getMapName()
   * @generated
   */
  EReference getMapName_Metodo();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.MapName#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see org.xtext.example.mydsl.rest.MapName#getParam()
   * @see #getMapName()
   * @generated
   */
  EReference getMapName_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Metodo <em>Metodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metodo</em>'.
   * @see org.xtext.example.mydsl.rest.Metodo
   * @generated
   */
  EClass getMetodo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Metodo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.Metodo#getName()
   * @see #getMetodo()
   * @generated
   */
  EAttribute getMetodo_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Metodo#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.example.mydsl.rest.Metodo#getPath()
   * @see #getMetodo()
   * @generated
   */
  EReference getMetodo_Path();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Metodo#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Response</em>'.
   * @see org.xtext.example.mydsl.rest.Metodo#getResponse()
   * @see #getMetodo()
   * @generated
   */
  EReference getMetodo_Response();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.DELETE <em>DELETE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DELETE</em>'.
   * @see org.xtext.example.mydsl.rest.DELETE
   * @generated
   */
  EClass getDELETE();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.POST <em>POST</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>POST</em>'.
   * @see org.xtext.example.mydsl.rest.POST
   * @generated
   */
  EClass getPOST();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.POST#getRequest <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Request</em>'.
   * @see org.xtext.example.mydsl.rest.POST#getRequest()
   * @see #getPOST()
   * @generated
   */
  EReference getPOST_Request();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.PUT <em>PUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PUT</em>'.
   * @see org.xtext.example.mydsl.rest.PUT
   * @generated
   */
  EClass getPUT();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.PUT#getRequest <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Request</em>'.
   * @see org.xtext.example.mydsl.rest.PUT#getRequest()
   * @see #getPUT()
   * @generated
   */
  EReference getPUT_Request();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.GET <em>GET</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GET</em>'.
   * @see org.xtext.example.mydsl.rest.GET
   * @generated
   */
  EClass getGET();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Response <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Response</em>'.
   * @see org.xtext.example.mydsl.rest.Response
   * @generated
   */
  EClass getResponse();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Response#getTipoResponse <em>Tipo Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Response</em>'.
   * @see org.xtext.example.mydsl.rest.Response#getTipoResponse()
   * @see #getResponse()
   * @generated
   */
  EReference getResponse_TipoResponse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Response#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.xtext.example.mydsl.rest.Response#isArray()
   * @see #getResponse()
   * @generated
   */
  EAttribute getResponse_Array();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Request <em>Request</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Request</em>'.
   * @see org.xtext.example.mydsl.rest.Request
   * @generated
   */
  EClass getRequest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Request#getTipoResponse <em>Tipo Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Response</em>'.
   * @see org.xtext.example.mydsl.rest.Request#getTipoResponse()
   * @see #getRequest()
   * @generated
   */
  EReference getRequest_TipoResponse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Request#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.xtext.example.mydsl.rest.Request#isArray()
   * @see #getRequest()
   * @generated
   */
  EAttribute getRequest_Array();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.URL <em>URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>URL</em>'.
   * @see org.xtext.example.mydsl.rest.URL
   * @generated
   */
  EClass getURL();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.URL#getPathparam <em>Pathparam</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pathparam</em>'.
   * @see org.xtext.example.mydsl.rest.URL#getPathparam()
   * @see #getURL()
   * @generated
   */
  EReference getURL_Pathparam();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.URL#getQueryparam <em>Queryparam</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Queryparam</em>'.
   * @see org.xtext.example.mydsl.rest.URL#getQueryparam()
   * @see #getURL()
   * @generated
   */
  EReference getURL_Queryparam();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.PathParam <em>Path Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Param</em>'.
   * @see org.xtext.example.mydsl.rest.PathParam
   * @generated
   */
  EClass getPathParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.PathParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.PathParam#getName()
   * @see #getPathParam()
   * @generated
   */
  EAttribute getPathParam_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.QueryParam <em>Query Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Param</em>'.
   * @see org.xtext.example.mydsl.rest.QueryParam
   * @generated
   */
  EClass getQueryParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.QueryParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.QueryParam#getName()
   * @see #getQueryParam()
   * @generated
   */
  EAttribute getQueryParam_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Entidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad</em>'.
   * @see org.xtext.example.mydsl.rest.Entidad
   * @generated
   */
  EClass getEntidad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Entidad#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.Entidad#getName()
   * @see #getEntidad()
   * @generated
   */
  EAttribute getEntidad_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.rest.Entidad#getAtributos <em>Atributos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atributos</em>'.
   * @see org.xtext.example.mydsl.rest.Entidad#getAtributos()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_Atributos();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.EntidadMock <em>Entidad Mock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad Mock</em>'.
   * @see org.xtext.example.mydsl.rest.EntidadMock
   * @generated
   */
  EClass getEntidadMock();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.EntidadSimple <em>Entidad Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad Simple</em>'.
   * @see org.xtext.example.mydsl.rest.EntidadSimple
   * @generated
   */
  EClass getEntidadSimple();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Atributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo</em>'.
   * @see org.xtext.example.mydsl.rest.Atributo
   * @generated
   */
  EClass getAtributo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Atributo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo</em>'.
   * @see org.xtext.example.mydsl.rest.Atributo#getTipo()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_Tipo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Atributo#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.xtext.example.mydsl.rest.Atributo#isArray()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_Array();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Atributo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.Atributo#getName()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.rest.Atributo#getMocktype <em>Mocktype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mocktype</em>'.
   * @see org.xtext.example.mydsl.rest.Atributo#getMocktype()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_Mocktype();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.Mock <em>Mock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mock</em>'.
   * @see org.xtext.example.mydsl.rest.Mock
   * @generated
   */
  EClass getMock();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.Mock#isPk <em>Pk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pk</em>'.
   * @see org.xtext.example.mydsl.rest.Mock#isPk()
   * @see #getMock()
   * @generated
   */
  EAttribute getMock_Pk();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.TipoElemento <em>Tipo Elemento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Elemento</em>'.
   * @see org.xtext.example.mydsl.rest.TipoElemento
   * @generated
   */
  EClass getTipoElemento();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.TipoEntidad <em>Tipo Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Entidad</em>'.
   * @see org.xtext.example.mydsl.rest.TipoEntidad
   * @generated
   */
  EClass getTipoEntidad();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.rest.TipoEntidad#getEntidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entidad</em>'.
   * @see org.xtext.example.mydsl.rest.TipoEntidad#getEntidad()
   * @see #getTipoEntidad()
   * @generated
   */
  EReference getTipoEntidad_Entidad();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.rest.TipoBasico <em>Tipo Basico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tipo Basico</em>'.
   * @see org.xtext.example.mydsl.rest.TipoBasico
   * @generated
   */
  EClass getTipoBasico();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.rest.TipoBasico#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.rest.TipoBasico#getName()
   * @see #getTipoBasico()
   * @generated
   */
  EAttribute getTipoBasico_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestFactory getRestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.ModelImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTIDADES = eINSTANCE.getModel_Entidades();

    /**
     * The meta object literal for the '<em><b>Metodos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__METODOS = eINSTANCE.getModel_Metodos();

    /**
     * The meta object literal for the '<em><b>Tests</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TESTS = eINSTANCE.getModel_Tests();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.TestImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__NAME = eINSTANCE.getTest_Name();

    /**
     * The meta object literal for the '<em><b>Service</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__SERVICE = eINSTANCE.getTest_Service();

    /**
     * The meta object literal for the '<em><b>Mapping</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__MAPPING = eINSTANCE.getTest_Mapping();

    /**
     * The meta object literal for the '<em><b>Assertion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__ASSERTION = eINSTANCE.getTest_Assertion();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.AssertionImpl <em>Assertion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.AssertionImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAssertion()
     * @generated
     */
    EClass ASSERTION = eINSTANCE.getAssertion();

    /**
     * The meta object literal for the '<em><b>Assert Response</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERTION__ASSERT_RESPONSE = eINSTANCE.getAssertion_AssertResponse();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.AssertResponseImpl <em>Assert Response</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.AssertResponseImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAssertResponse()
     * @generated
     */
    EClass ASSERT_RESPONSE = eINSTANCE.getAssertResponse();

    /**
     * The meta object literal for the '<em><b>Comparacion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_RESPONSE__COMPARACION = eINSTANCE.getAssertResponse_Comparacion();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.ComparacionImpl <em>Comparacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.ComparacionImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getComparacion()
     * @generated
     */
    EClass COMPARACION = eINSTANCE.getComparacion();

    /**
     * The meta object literal for the '<em><b>Entidad</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARACION__ENTIDAD = eINSTANCE.getComparacion_Entidad();

    /**
     * The meta object literal for the '<em><b>Atributo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARACION__ATRIBUTO = eINSTANCE.getComparacion_Atributo();

    /**
     * The meta object literal for the '<em><b>Metodo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARACION__METODO = eINSTANCE.getComparacion_Metodo();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARACION__PARAM = eINSTANCE.getComparacion_Param();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.MappingImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Maps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__MAPS = eINSTANCE.getMapping_Maps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.MapImpl <em>Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.MapImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMap()
     * @generated
     */
    EClass MAP = eINSTANCE.getMap();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP__NAME = eINSTANCE.getMap_Name();

    /**
     * The meta object literal for the '<em><b>Entidad Map</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP__ENTIDAD_MAP = eINSTANCE.getMap_EntidadMap();

    /**
     * The meta object literal for the '<em><b>Atributo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP__ATRIBUTO = eINSTANCE.getMap_Atributo();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.MapNameImpl <em>Map Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.MapNameImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMapName()
     * @generated
     */
    EClass MAP_NAME = eINSTANCE.getMapName();

    /**
     * The meta object literal for the '<em><b>Metodo</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_NAME__METODO = eINSTANCE.getMapName_Metodo();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_NAME__PARAM = eINSTANCE.getMapName_Param();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.MetodoImpl <em>Metodo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.MetodoImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMetodo()
     * @generated
     */
    EClass METODO = eINSTANCE.getMetodo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METODO__NAME = eINSTANCE.getMetodo_Name();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO__PATH = eINSTANCE.getMetodo_Path();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METODO__RESPONSE = eINSTANCE.getMetodo_Response();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.DELETEImpl <em>DELETE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.DELETEImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getDELETE()
     * @generated
     */
    EClass DELETE = eINSTANCE.getDELETE();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.POSTImpl <em>POST</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.POSTImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPOST()
     * @generated
     */
    EClass POST = eINSTANCE.getPOST();

    /**
     * The meta object literal for the '<em><b>Request</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POST__REQUEST = eINSTANCE.getPOST_Request();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.PUTImpl <em>PUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.PUTImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPUT()
     * @generated
     */
    EClass PUT = eINSTANCE.getPUT();

    /**
     * The meta object literal for the '<em><b>Request</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__REQUEST = eINSTANCE.getPUT_Request();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.GETImpl <em>GET</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.GETImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getGET()
     * @generated
     */
    EClass GET = eINSTANCE.getGET();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.ResponseImpl <em>Response</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.ResponseImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getResponse()
     * @generated
     */
    EClass RESPONSE = eINSTANCE.getResponse();

    /**
     * The meta object literal for the '<em><b>Tipo Response</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESPONSE__TIPO_RESPONSE = eINSTANCE.getResponse_TipoResponse();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESPONSE__ARRAY = eINSTANCE.getResponse_Array();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.RequestImpl <em>Request</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.RequestImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getRequest()
     * @generated
     */
    EClass REQUEST = eINSTANCE.getRequest();

    /**
     * The meta object literal for the '<em><b>Tipo Response</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUEST__TIPO_RESPONSE = eINSTANCE.getRequest_TipoResponse();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUEST__ARRAY = eINSTANCE.getRequest_Array();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.URLImpl <em>URL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.URLImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getURL()
     * @generated
     */
    EClass URL = eINSTANCE.getURL();

    /**
     * The meta object literal for the '<em><b>Pathparam</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference URL__PATHPARAM = eINSTANCE.getURL_Pathparam();

    /**
     * The meta object literal for the '<em><b>Queryparam</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference URL__QUERYPARAM = eINSTANCE.getURL_Queryparam();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.PathParamImpl <em>Path Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.PathParamImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getPathParam()
     * @generated
     */
    EClass PATH_PARAM = eINSTANCE.getPathParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH_PARAM__NAME = eINSTANCE.getPathParam_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.QueryParamImpl <em>Query Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.QueryParamImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getQueryParam()
     * @generated
     */
    EClass QUERY_PARAM = eINSTANCE.getQueryParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY_PARAM__NAME = eINSTANCE.getQueryParam_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.EntidadImpl <em>Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.EntidadImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidad()
     * @generated
     */
    EClass ENTIDAD = eINSTANCE.getEntidad();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDAD__NAME = eINSTANCE.getEntidad_Name();

    /**
     * The meta object literal for the '<em><b>Atributos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__ATRIBUTOS = eINSTANCE.getEntidad_Atributos();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.EntidadMockImpl <em>Entidad Mock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.EntidadMockImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidadMock()
     * @generated
     */
    EClass ENTIDAD_MOCK = eINSTANCE.getEntidadMock();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.EntidadSimpleImpl <em>Entidad Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.EntidadSimpleImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getEntidadSimple()
     * @generated
     */
    EClass ENTIDAD_SIMPLE = eINSTANCE.getEntidadSimple();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.AtributoImpl <em>Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.AtributoImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getAtributo()
     * @generated
     */
    EClass ATRIBUTO = eINSTANCE.getAtributo();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__TIPO = eINSTANCE.getAtributo_Tipo();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__ARRAY = eINSTANCE.getAtributo_Array();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__NAME = eINSTANCE.getAtributo_Name();

    /**
     * The meta object literal for the '<em><b>Mocktype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__MOCKTYPE = eINSTANCE.getAtributo_Mocktype();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.MockImpl <em>Mock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.MockImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getMock()
     * @generated
     */
    EClass MOCK = eINSTANCE.getMock();

    /**
     * The meta object literal for the '<em><b>Pk</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOCK__PK = eINSTANCE.getMock_Pk();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.TipoElementoImpl <em>Tipo Elemento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.TipoElementoImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoElemento()
     * @generated
     */
    EClass TIPO_ELEMENTO = eINSTANCE.getTipoElemento();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.TipoEntidadImpl <em>Tipo Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.TipoEntidadImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoEntidad()
     * @generated
     */
    EClass TIPO_ENTIDAD = eINSTANCE.getTipoEntidad();

    /**
     * The meta object literal for the '<em><b>Entidad</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIPO_ENTIDAD__ENTIDAD = eINSTANCE.getTipoEntidad_Entidad();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.rest.impl.TipoBasicoImpl <em>Tipo Basico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.rest.impl.TipoBasicoImpl
     * @see org.xtext.example.mydsl.rest.impl.RestPackageImpl#getTipoBasico()
     * @generated
     */
    EClass TIPO_BASICO = eINSTANCE.getTipoBasico();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO_BASICO__NAME = eINSTANCE.getTipoBasico_Name();

  }

} //RestPackage
