/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.RestStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RestStandaloneSetup extends RestStandaloneSetupGenerated {
  public static void doSetup() {
    new RestStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
