/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.RestRuntimeModule;
import org.xtext.example.mydsl.RestStandaloneSetup;
import org.xtext.example.mydsl.ide.RestIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RestIdeSetup extends RestStandaloneSetup {
  @Override
  public Injector createInjector() {
    RestRuntimeModule _restRuntimeModule = new RestRuntimeModule();
    RestIdeModule _restIdeModule = new RestIdeModule();
    return Guice.createInjector(Modules2.mixin(_restRuntimeModule, _restIdeModule));
  }
}
