/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.rest.ui.internal.RestActivator;

public class RestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RestActivator.getInstance().getInjector("org.xtext.example.mydsl.Rest");
	}

}
