/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.rest.ui.internal.RestActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RestActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RestActivator.getInstance().getInjector(RestActivator.ORG_XTEXT_EXAMPLE_MYDSL_REST);
	}
	
}
