/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.rest.EntidadSimple;
import org.xtext.example.mydsl.rest.RestPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entidad Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntidadSimpleImpl extends EntidadImpl implements EntidadSimple
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntidadSimpleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestPackage.Literals.ENTIDAD_SIMPLE;
  }

} //EntidadSimpleImpl
