/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.rest.Entidad;
import org.xtext.example.mydsl.rest.Metodo;
import org.xtext.example.mydsl.rest.Model;
import org.xtext.example.mydsl.rest.RestPackage;
import org.xtext.example.mydsl.rest.Test;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rest.impl.ModelImpl#getEntidades <em>Entidades</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.impl.ModelImpl#getMetodos <em>Metodos</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rest.impl.ModelImpl#getTests <em>Tests</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getEntidades() <em>Entidades</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntidades()
   * @generated
   * @ordered
   */
  protected EList<Entidad> entidades;

  /**
   * The cached value of the '{@link #getMetodos() <em>Metodos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetodos()
   * @generated
   * @ordered
   */
  protected EList<Metodo> metodos;

  /**
   * The cached value of the '{@link #getTests() <em>Tests</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTests()
   * @generated
   * @ordered
   */
  protected EList<Test> tests;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Entidad> getEntidades()
  {
    if (entidades == null)
    {
      entidades = new EObjectContainmentEList<Entidad>(Entidad.class, this, RestPackage.MODEL__ENTIDADES);
    }
    return entidades;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Metodo> getMetodos()
  {
    if (metodos == null)
    {
      metodos = new EObjectContainmentEList<Metodo>(Metodo.class, this, RestPackage.MODEL__METODOS);
    }
    return metodos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Test> getTests()
  {
    if (tests == null)
    {
      tests = new EObjectContainmentEList<Test>(Test.class, this, RestPackage.MODEL__TESTS);
    }
    return tests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RestPackage.MODEL__ENTIDADES:
        return ((InternalEList<?>)getEntidades()).basicRemove(otherEnd, msgs);
      case RestPackage.MODEL__METODOS:
        return ((InternalEList<?>)getMetodos()).basicRemove(otherEnd, msgs);
      case RestPackage.MODEL__TESTS:
        return ((InternalEList<?>)getTests()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RestPackage.MODEL__ENTIDADES:
        return getEntidades();
      case RestPackage.MODEL__METODOS:
        return getMetodos();
      case RestPackage.MODEL__TESTS:
        return getTests();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RestPackage.MODEL__ENTIDADES:
        getEntidades().clear();
        getEntidades().addAll((Collection<? extends Entidad>)newValue);
        return;
      case RestPackage.MODEL__METODOS:
        getMetodos().clear();
        getMetodos().addAll((Collection<? extends Metodo>)newValue);
        return;
      case RestPackage.MODEL__TESTS:
        getTests().clear();
        getTests().addAll((Collection<? extends Test>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.MODEL__ENTIDADES:
        getEntidades().clear();
        return;
      case RestPackage.MODEL__METODOS:
        getMetodos().clear();
        return;
      case RestPackage.MODEL__TESTS:
        getTests().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RestPackage.MODEL__ENTIDADES:
        return entidades != null && !entidades.isEmpty();
      case RestPackage.MODEL__METODOS:
        return metodos != null && !metodos.isEmpty();
      case RestPackage.MODEL__TESTS:
        return tests != null && !tests.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
