/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.rest.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.rest.RestPackage;
import org.xtext.example.mydsl.rest.TipoElemento;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tipo Elemento</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TipoElementoImpl extends MinimalEObjectImpl.Container implements TipoElemento
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TipoElementoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RestPackage.Literals.TIPO_ELEMENTO;
  }

} //TipoElementoImpl
